[buildPlans.KnoxMono]
family = "Knox Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
buildTextureFeature = true

[buildPlans.KnoxMono.variants]
inherits = "ss14"

[buildPlans.KnoxMono.variants.design]
one = "base"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "semi-open-non-crossing-serifless"
five = "upright-arched-serifless"
six = "open-contour"
seven = "bend-serifless"
eight = "crossing-asymmetric"
nine = "open-contour"
zero = "slashed"
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifed-symmetric"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-corner-serifless"
capital-v = "curly-serifless"
capital-w = "straight-serifless"
capital-x = "straight-serifless"
capital-y = "straight-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-corner-serifed"
b = "toothless-corner-serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "serifless"
g = "single-storey-earless-corner"
i = "serifed-flat-tailed"
j = "serifed"
k = "straight-serifless"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-corner-serifless"
v = "straight-serifless"
w = "curly-serifless"
y = "straight-serifless"
punctuation-dot = "round"
tilde = "low"
asterisk = "penta-low"
underscore = "low"
paren = "normal"
brace = "curly"
number-sign = "slanted"
at = "compact"
cent = "bar-interrupted"
percent = "dots"
question = "smooth"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.KnoxMono.ligations]
inherits = "default-calt"
enables = [
  "eqeqeq", # Triple-line equality ligation
  "exeqeq", # Triple-line inequality ligation
]
[buildPlans.KnoxMono.weights.Regular]
shape = 415
menu = 400
css = 400
[buildPlans.KnoxMono.weights.Bold]
shape = 700
menu = 700
css = 700
[buildPlans.KnoxMono.weights.Medium]
shape = 510
menu = 500
css = 500
[buildPlans.KnoxMono.widths.Normal]
shape = 604
menu = 5
css = "normal"
[buildPlans.KnoxMono.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
[buildPlans.KnoxMono.slopes.Italic]
angle = 9.5
shape = "italic"
menu = "italic"
css = "italic"
# Metric overrides
[buildPlans.KnoxMono.metricOverride]
xHeight = 540
cap = 720
ascender = 735
sb = 'blend(weight, [400, 90], [700, 78])'
accentWidth = 200
accentClearance = 80
accentHeight = 170
accentStackOffset = 208
leading = 1170
parenSize = 950
periodSize = 150
essRatio = 1.03
essRatioUpper = 1.03
essRatioLower = 1.03
essRatioQuestion = 1.03
archDepth = 185
smallArchDepth = 190
